export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const CREATE_PRODUCTS = 'CREATE_PRODUCTS';
export const FILTER_PRODUCTS_BY_SIZE = 'FILTER_PRODUCTS_BY_SIZE';
export const ORDER_PRODUCTS_BY_PRICE = 'ORDER_PRODUCTS_BY_PRICE';